### ISSUE TITLE
Failure with some svg tags

### ISSUE THREAD

**Issue by MoOx** [jhamlet/svg-react-loader#12]
```
ModuleParseError: Module parse failed: /Users/MoOx/Sync/Development/statinamic/docs/node_modules/svg-react-loader/index.js!/Users/MoOx/Sync/Development/statinamic/logo/statinamic-text.svg Line 21: Unexpected token <
You may need an appropriate loader to handle this file type.
| 
|         return (
|             <svg {...this.props}>
|                   <title>statinamic</title>
|   <desc>Created with Sketch.</desc>
```

It seems desc and title should be removed.

**Comment by jhamlet** [comment]
Do you have a svg file you can attach that I can reproduce the issue?

**Comment by MoOx** [comment]
https://raw.githubusercontent.com/MoOx/statinamic/master/logo/statinamic-text.svg

A workaround is using svgo-loader before with { removeTitle: true } in plugins.

**Comment by jhamlet** [comment]
`title` and `desc` are [valid svg element tag names](https://developer.mozilla.org/en-US/docs/Web/SVG/Element)... but, [maybe not within React](https://facebook.github.io/react/docs/tags-and-attributes.html)...

Are you using babel in your loader pipeline?

**Comment by MoOx** [comment]
I was using it in a weird context, on server side https://github.com/istarkov/babel-plugin-webpack-loaders, so got stuck with another issue.
