### ISSUE TITLE
Strip or "simplify" imported SVGs

### ISSUE THREAD

**Issue by nfarina** [jhamlet/svg-react-loader#17]
This is just an idea; feel free to close!

I'm currently looking at a designer-friendly workflow of creating icons in Sketch, exporting them to individual SVG files, then including them in my React app via `svg-react-loader` (which is awesome).

One desirable feature of "icon" artwork specifically is the ability to treat the shapes as "uncolored" by default, then apply the current text color via the CSS `fill: currentcolor` property. Currently I'm manually stripping out color-related attributes from the raw SVG source. But it would be really handy if this plugin could optionally do this for me!

Additionally, Sketch exports "extraneous" SVG elements like `title` and `desc` which just bloat the final DOM. Would be great to remove these as well.

**Comment by jhamlet** [comment]
@nfarina Thanks for the ideas and the nice comments.

There are two other issues I want to resolve: [#11](https://github.com/jhamlet/svg-react-loader/issues/11), and [#12](https://github.com/jhamlet/svg-react-loader/issues/12) which might address some of the things you want to do.

[#11](https://github.com/jhamlet/svg-react-loader/issues/11) would change the loader API quite a bit, as it would expect an object tree representing the XML/SVG, but it would open up the pipeline so you can insert an intermediate loader to "transform" the tree to whatever you would like... this is still on my drawing board.

In the meantime, have you checked out [svgo](https://github.com/svg/svgo) and its associated [loader](https://www.npmjs.com/package/svgo-loader)?

;-j

**Comment by nfarina** [comment]
Oh wow - `svgo` is exactly what I needed! I just put it on the front of my pipeline and it does everything I want. Feel free to close this and thanks for pointing out that module.

**Comment by jhamlet** [comment]
np.

I use it as a "pre-loader" in webpack.
