### ISSUE TITLE
Pass SVG in as a variable

### ISSUE THREAD

**Issue by tonydiaz** [jhamlet/svg-react-loader#2]
I want to be able to pass an `svg` name into this react component and call it from the _render_ function. Is there currently a way to do this?

Something like this:
```javascript
var React   = require("react");
var Icon = require("babel!svg-react!");

var SVG = React.createClass({
    render: function() {
        return <Icon path="../node_modules/logo.svg" />
    }
});
```

**Comment by jhamlet** [comment]
Try this instead:

~~~js
var React  = require('react');
var Icon = require('bable!svg-react!../node_modules/logo.svg');

module.exports = React.createClass({
    render: function () {
        return <Icon />;
    }
})
~~~

**Comment by tonydiaz** [comment]
That way you hardcode the SVG filename. Anyway to pass in the filename? Something like this?

```javascript
var svgPath = "../files/svg/";

var SVG = React.createClass({
    render() {
        var Icon = require("babel!svg-react!" + svgPath + this.props.filename);
        return <Icon className={this.props.className}/>
    }
});
```

**Comment by jhamlet** [comment]
According to webpack it has [clever parsing](https://webpack.github.io/docs/what-is-webpack.html#clever-parsing) and will `require` all files in that directory. So, according to webpack it should work.

Otherwise, I'm not sure what use-case you are trying to solve, since webpack is going to include everything anyway.

`svg-react-loader` was not designed to load SVGs dynamically (over the internet). It was designed to allow webpack to include them at build time.

Maybe if you can describe in more detail what you are trying to solve, I can you help find a solution.

**Comment by tonydiaz** [comment]
Thanks. The use-case is a reusable component so when an SVG is loaded the caller will only need to call the name of the SVG and not need to fill out the entire path each time. 

I have a problem concatenating a string within a require statement. Do you think it is a `async` issue?

**Caller**
```javascript
var SVG = require("./svg.js")
var Comp = React.createClass({
    render() { 
      //Load some stuff
      <SVG name="play.svg" className="button" />
    }
```
**svg.js**
```javascript
var svgPath = "../files/svg/";

var SVG = React.createClass({
    render() {
        //I'm unable to get the line below to work. It seems the `require` doesn't like it 
        //when I concatenate a string
        var Icon = require("babel!svg-react!" + svgPath + this.props.filename);
        return <Icon className={this.props.className}/>
    }
});

```

**Comment by jhamlet** [comment]
The issue you describe seems to be a limitation of webpack.

If you wish to reduce the 'path' that consumers of these svgs need to know about, can I suggest trying it this way:

~~~js
// file: src/icons.js
module.exports = {
    Foo: require('babel!svg-react!../files/foo.svg'),
    Bar: require('babel!svg-react!../files/bar.svg'),
    Baz: require('babel!svg-react!../files/baz.svg'),
    // and so on ...
};
~~~

Then consumers can use it like so:

~~~js
// file: index.js
var React = require('react');
var IconFoo = require('./src/icons').Foo;

module.exports = React.createClass({
    render: function () {
        return <IconFoo className="foo" />;
    }
});
~~~


Alternatively, you try the following (I have not tested it).

This uses [`require.context`](http://webpack.github.io/docs/context.html#require-context) in webpack to do something more dynamic.

~~~js
// file: src/icons.js
var React = require('react');
var context = require.context('babel!svg-react!../files', false, /\.svg$/);

module.exports = React.createClass({
    render: function () {
        var name = this.props.iconName;
        var Icon = context(iconName + '.svg');

        return (
            Icon ?
                <Icon {...this.props} /> :
                <span className="missingIcon" />
        );
    }
});
~~~

Then other's can do the following:

~~~js
// file: index.js
var React = require('react');
var Icon = require('./src/icons');

module.exports = React.createClass({
    render: function () {
        return <Icon iconName='foo' />;
    }
});
~~~
