### ISSUE TITLE
SVGs using CRLF encoding doesn't work with inline stylesheets.

### ISSUE THREAD

**Issue by guncha** [jhamlet/svg-react-loader#20]
A random issue, but I just noticed that after exporting an icon from Illustrator the colors didn't display correctly. This is what the rendered DOM looks like:

![image](https://cloud.githubusercontent.com/assets/679632/15688014/0602ae58-2746-11e6-8b09-963e4225cef2.png)

It's that weird `&#xD;` stuff that is breaking the stylesheet. It seems like Illustrator exports SVGs with CRLF line endings by default, even if I'm on a Mac. Something something lowest common denominator. Then the `CR` part ends up being encoded in the stylesheet.

Sigh..

**Comment by jhamlet** [comment]
What system are you using Illustrator in (Windows, or Mac)?

How are you getting Illustrator to export a style block (Advanced Properties > CSS Properties > Style Elements)? 

What document encoding are you using (utf-8)?

Are you setting an encoding option on your outer html tag? The xml file produced by Illustrator sets the encoding in the xml tag, which is stripped when the SVG is turned into a react element. See if the colors show up if you add an `encoding="utf-8"` attribute.

**Comment by guncha** [comment]
This is happening with Illustrator CS6 on a Mac using CSS Properties -> Style Elements. Encoding is set to UTF-8. The page already has a `<meta charset="utf-8">` tag, so no change there. It only works if I convert the XML to use LF line endings.

**Comment by jhamlet** [comment]
How do you convert the XML to use linefeeds instead?

**Comment by guncha** [comment]
I am converting it from CRLF to just LF using my editor (Atom). Here, I'll upload an example SVG with CRLF line endings:

[profile.svg.zip](https://github.com/jhamlet/svg-react-loader/files/309583/profile.svg.zip)

The icon should be colored gold due to the `.st0 { fill: gold }` stylesheet, but it doesn't work due to this issue.

**Comment by jhamlet** [comment]
Closing. Reopen if you experience in version 0.4.0-beta.2 or greater
