### ISSUE TITLE
ReferenceError: React is not defined

### ISSUE THREAD

**Issue by whois42** [jhamlet/svg-react-loader#22]
Hello,
I testing my react application with Mocha and when I run npm test I got the exception: 

```
app/DOM/pure/landing-assets/logo.svg:3
React.createElement(
^

ReferenceError: React is not defined
```
In webpack config file I set this properties to svg: 
```
{
  test: /\.svg$/,
  loaders: DEBUG ? ['react-hot', 'babel', 'svg-react'] : ['babel', 'svg-react']
}
```
How I can solve this problem?

**Comment by jhamlet** [comment]
@whois42 Are you depending on `react` in your `package.json` file?

**Comment by whois42** [comment]
@jhamlet sure

**Comment by jhamlet** [comment]
Hmmm... I need a little more information/context on how you are running your Mocha tests... are they going through webpack?

Is the a repository you can point me to?

**Comment by whois42** [comment]
`"test": "mocha --compilers js:babel-register --recursive --require test/utils/dom.js --require mock-css-modules --require babel-polyfill --harmony-proxies"`

Sorry, I can't show you project, because it's a closed source
