### ISSUE TITLE
React v15

### ISSUE THREAD

**Issue by ccorcos** [jhamlet/svg-react-loader#24]
I'm getting a couple errors:

![image](https://cloud.githubusercontent.com/assets/1794527/16318102/6032e970-3942-11e6-9ca8-27ce6cf006df.png)

![image](https://cloud.githubusercontent.com/assets/1794527/16318105/68a5b394-3942-11e6-9e72-dd55554d7c64.png)

![image](https://cloud.githubusercontent.com/assets/1794527/16318112/70f4910a-3942-11e6-8316-69aac27e2e41.png)

**Comment by jhamlet** [comment]
This should be gone with v0.4.0-beta.2 as it no longer depends on babel, and applying properties after componentDidMount
