### ISSUE TITLE
Using the loader in a lib causes `You've loaded two copies of React on the page.`

### ISSUE THREAD

**Issue by Moezalez** [jhamlet/svg-react-loader#30]
When I use svg-react-loader in a library which I pack with webpack, the user using this package gets:

> Warning: React can't find the root component node for data-reactid value `.0.0.1.0.0.1.0.0.1.0.1.1.2.1.0.0`. If you're seeing this message, it probably means that you've loaded two copies of React on the page. At this time, only a single copy of React can be loaded at a time.

If I remove the SVG components, it works fine.

I import them like this:
```JavaScript
  Pic = require('babel!svg-react!./assets/pic.svg?name=Pic')
```

Using them within a project (not via a lib) works fine.

**Comment by jhamlet** [comment]
Can you describe what you mean by a "lib"?

If you mean something similar to an `npm package`, with its own dependencies, I can see how that could cause a problem. Is this library also depending on React?

**Comment by Moezalez** [comment]
yes. 
I resolved by declaring react as an external in webpack. :)
