### ISSUE TITLE
change fillColor?

### ISSUE THREAD

**Issue by SkateFreak** [jhamlet/svg-react-loader#34]
is it possible to change the fill color of the svg?

thanks

**Comment by gor181** [comment]
If anyone finds it helpful you can specify a `className` directly on the Icon element.
Then define css as:

```
.someClassName g {
    fill: 'red';
}
```

That one should paint it red.

**Comment by SkateFreak** [comment]
@gor181 yeah i also found out that ```svgs``` are equipped with ```.cls-1``` class and sometimes even ```<style>``` tags, which make it hard to maintain through css.

i ended up cleaning my svg files source code

**Comment by pauldcollins** [comment]
Thanks for this @gor181 - it works!

Just wondering if there's an inline solution, that we can pass down as props, instead of having to create a CSS class for every color? Can't see it as an option in the docs/

Thanks for any help.

**Comment by tamasPetki** [comment]
const iconColor = "black";

and then add this in your render() method:

<style>
        {`
    svg path{
      fill: ${iconColor};
    }
    `}
</style>
