### ISSUE TITLE
MIT License amendment

### ISSUE THREAD

**Issue by hunthunthunt** [jhamlet/svg-react-loader#35]
The MIT-style license for this package contains the line:

> "The Software shall be used for Good, not Evil."

While I appreciate the sentiment of this statement, from a legal standpoint, it is problematic as this is now no longer free software - see the discussion here:

http://programmers.stackexchange.com/questions/47028/how-could-we-rewrite-the-no-evil-license-to-make-it-free

More information here:
https://en.wikipedia.org/wiki/Douglas_Crockford#.22Good.2C_not_Evil.22

I kindly request you to reconsider the addition of this line, as I would like to use this software, but am unable to do so given the current license.

**Comment by tera-sinube** [comment]
@hunthunthunt as I do not see what evil could come from using SVGs as React components, I will change the license with release 0.4.0

**Comment by jhamlet** [comment]
@hunthunthunt as I do not see what evil could come from using SVGs as React components, I will change the license with release 0.4.0
