### ISSUE TITLE
Warning: Unknown prop `dataName` on <g> tag.

### ISSUE THREAD

**Issue by SkateFreak** [jhamlet/svg-react-loader#36]
warning.js:36 Warning: Unknown prop `dataName` on <g> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop

**Comment by jhamlet** [comment]
@SkateFreak v0.4.0 should address this. You can try it out by `npm install svg-react-loader@next`

**Comment by quinn** [comment]
if anyone else has this bug upgrading did not help, but I was able to edit the SVG file and remove the `data-name` attribute there which fixed this.
