### ISSUE TITLE
react gives errors on unknown props

### ISSUE THREAD

**Issue by Inoir** [jhamlet/svg-react-loader#37]
Maybe its possible to check the imported svg for non svg properties and remove them?

react 15.2.0 added:

> Add warning for unknown properties on DOM elements

[Unknown prop warning](https://facebook.github.io/react/warnings/unknown-prop.html)

**Comment by jhamlet** [comment]
This should be fixed with the next version. (It doesn't use any special attributes to manage non-react attributes on component mounting.)

Try `npm install svg-react-loader@next` to see if this goes away.
