### ISSUE TITLE
SyntaxError v0.4.0-beta.2

### ISSUE THREAD

**Issue by Inoir** [jhamlet/svg-react-loader#39]
Hey ive tried the new version, so i can test the "unknown prop" solution.

Now ive got another issue on my svg named Carline_(TT).
Reason for that error: the lib is creating an function to return a new React element. The second part of the name ("_(TT)") will be in these created function name. So it looks like this at the end:

`function Carline(TT) (props) { ... }`

This is throwing an syntax error.
Is it possible to check the name before creating the function? I can easy resolve these error for the moment.

**Comment by tera-sinube** [comment]
@Inoir Take a look at the `name` query parameter, and the [examples](https://github.com/jhamlet/svg-react-loader/blob/version-0.4.0/README.md#examples) webpack config for how to use webpack generated names.
