### ISSUE TITLE
ReactDOM with React 0.14.0

### ISSUE THREAD

**Issue by ccorcos** [jhamlet/svg-react-loader#4]
> Warning: React.findDOMNode is deprecated. Please use ReactDOM.findDOMNode from require('react-dom') instead.

https://github.com/jhamlet/svg-react-loader/blob/master/helpers.js#L28

**Comment by jhamlet** [comment]
Fixed with commit f55ad5b1733b967ab3d5deef7b8b0a6619dae1f2
