### ISSUE TITLE
Using without webpack

### ISSUE THREAD

**Issue by nescalante** [jhamlet/svg-react-loader#45]
Quick and short, is it possible to use this package without webpack?

I am building my lib using babel-cli but since this seems to be a webpack loader, I am not achieving the goal.

Is there a way to use this as a babel transformer?

Thanks in advance.

**Comment by jhamlet** [comment]
@nescalante Not at this time. Maybe in the future.

**Comment by neoziro** [comment]
@nescalante you should take a look at [svgr](https://github.com/smooth-code/svgr).

**Comment by rwieruch** [comment]
If I am using Webpack, what's the difference to SVGR? I can only think of a more fine-grained control level when using SVGR integrated in Webpack, otherwise the most straightforward way would be using this loader.
