### ISSUE TITLE
Module build failed: SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by aleen42** [jhamlet/svg-react-loader#47]
I have a component written like this:

```js
import MountainSVGSrc from 'babel!svg-react!./lightMountain.svg?name=MountainSVGSrc';

export class MyComponent {
    /** ... */
    render () {
        return (
            <div>
                <MountaniSVGSrc />
            </div>
        );
    }
}
```

When building with webpack, it throws an error which states that failed to build this module, as the following figure shown:

![image](https://cloud.githubusercontent.com/assets/9573300/20186770/3bb9f70e-a7ac-11e6-904a-e7a7bf57b250.png)

And my configuration of webpack is shown as followed:

```js
/** svg */
{
    test: /\.svg$/,
    loader: 'babel!svg-react',
    query: {
        presets: ['es2015', 'react']
    }
}
```

**Comment by arnoldsandoval** [comment]
:+1:

**Comment by arnoldsandoval** [comment]
+1

**Comment by jhamlet** [comment]
@aleen42 That looks like a `babel` error.

I think your loaders on the import path are overriding your webpack configured presets.

Try

```js
import MountainSVGSrc from './lightMountain.svg?name=MountainSVGSrc';
```

or,

```
import MountainSVGSrc from 'babel?presets[]=es2015&presets[]=react!svg-react!./lightMountain.svg?name=MountainSVGSrc';
```

**Comment by jhamlet** [comment]
@aleen42 There's also a way to configure `babel` globally in the `webpack.config.js` file, but I can't recall off the top of my head.

**Comment by aleen42** [comment]
@jhamlet If trying the preceding code, it will arise the errors of trying another appropriate loader:

![image](https://cloud.githubusercontent.com/assets/9573300/20238156/c7a40c86-a91f-11e6-8e66-b377f3f7dc44.png)

**Comment by jhamlet** [comment]
@aleen42 @arnoldsandoval is this still an issue?

**Comment by jstray** [comment]
I'm getting the same error trying to use pui-collapse.

`import BaseCollapse from 'pui-react-collapse'`

gives

```
WARNING in ./~/babel-loader/lib!./~/svg-react-loader!./~/pui-css-iconography/svgs/zoom_out.svg
Module build failed: SyntaxError: Unexpected token (21:12)

  19 | 
  20 |         return (
> 21 |             <svg {...this.props}>
     |             ^

```

I have npm install'd babel-loaded and svg-react-loader, but it looks like we are missing the jsx translation somewhere in this pipeline. Any ideas?

This is my webpack config:
```
var path = require("path")
var webpack = require('webpack')
var BundleTracker = require('webpack-bundle-tracker')

module.exports = {
  context: __dirname,

  // Each page gets its own bundle
  entry: {
    workflows: './assets/js/workflows',
    workflow: './assets/js/workflow'
  },

  output: {
    path: path.resolve('./assets/bundles/'),
    filename: "[name]-[hash].js",
  },

  plugins: [
    new BundleTracker({filename: './webpack-stats.json'}),
  ],

  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        query: {presets: ['es2015', 'react']}  // to transform JSX into JS
      },
      {
        test: /\.css$/,
        loader: 'style-loader!css-loader'
      }
    ]
  },

  resolve: {
    modulesDirectories: ['node_modules'],
    extensions: ['', '.js', '.jsx']
  },
}
```

**Comment by jhamlet** [comment]
@jstray I do not see a 'svn-react-loader' setting in your `exports.module.loaders`

**Comment by jstray** [comment]
That seemed like it might be the problem, so I added

```
      {
        test: /\.svg$/, loader: 'babel?presets[]=es2015,presets[]=react!svg-react'
      }
```

But nope, didn't make it go away. I think that svg-react is ultimately being called from the npm module pui_react-svg svg.js:

```
    key: 'svgPathLoader',
    value: function svgPathLoader(src) {
      try {
        return require('!!babel!svg-react!../../app/svg/' + src + '.svg');
      } catch (e) {}
    }
```

And that looks like the same loader pipe, except perhaps it assumes babel is set up to use react presets?

**Comment by jhamlet** [comment]
@jstray that was going to be my next suggestion (.babelrc)

The double exclamation in that require statement is telling webpack to ignore other loaders configurations. So, the babelrc file configuration is the only alternative.

**Comment by HazelHyeji** [comment]
@jstray Thanks! I forgot babelrc file in my project folder.. you remind me!! I spent too much time on it. Thanks a million!

**Comment by Manivannan27** [comment]
Actually in my project i am facing this error
Module build failed: SyntaxError: const {className, css Module, dataBox, ...attributes} = this.props;

I am trying to solve this error if some one can able to resolve this error means please try to do it
