### ISSUE TITLE
Support simple text tags

### ISSUE THREAD

**Issue by jeron-diovis** [jhamlet/svg-react-loader#5]
Hi. I'm using your plugin (very useful one, need to say), and found a problem.

I managed to break everything down with this simple structure:

```xml
<svg>
    <title>Text</title>
</svg>
```

It falls into recursion [here](https://github.com/jhamlet/svg-react-loader/blob/master/utility%2Fsanitize.js#L98), endlessly invoking `sanitize` for key `0` of the same string.

I added this at the very beginning of `sanitize` function and it helped:
```js
if (typeof xmlNode === "string") {
    return xmlNode;
}
```
Don't know whether it's correct.

Please fix this.

**Comment by jhamlet** [comment]
@jeron-diovis Thanks for the report, and the useful investigation.

I'll dig in deeper as soon as I can.

**Comment by jhamlet** [comment]
I've made an attempt at getting it to work.

Can you try it on your project to see if it handles your current use-cases?

You can point your `svg-react-loader` dependency to `git+https://github.com/jhamlet/svg-react-loader#33445b3dd9e4de57128a7c6860df5104d99b7d9c` to get the unpublished changes.

;-j

**Comment by jeron-diovis** [comment]
Now it works fine for me.

**Comment by jhamlet** [comment]
Cool. Merging to master.
