### ISSUE TITLE
Empty Element Renders

### ISSUE THREAD

**Issue by Mingling94** [jhamlet/svg-react-loader#56]
Following the directions on your README and this [blog](https://diessi.ca/blog/svg-images-as-react-components-with-webpack/#comment-3147334892), I keep getting an empty element that doesn't show the svg. Any ideas?
![My Results](https://uploads.disquscdn.com/images/23ab97594a3ccdcefe33c484440349c8c19d8e9f83013a21cbfe8b28fe792870.png)

My svg file is proper.
webpack.config.js (or at least the one that matters, I have configs for each environment but they `webpack-merge` with this one):
```js
// webpack config
const webpack = require('webpack');
const path = require('path');

module.exports = function() {
  return {
    context: path.join(__dirname, '..', '..'),
    entry: './src/index.jsx',
    output: {
      path: './build/',
      filename: 'bundle.js',
      sourceMapFilename: 'map',
    },
    module: {
      rules: [
        {
          test: /\.(js|jsx)$/,
          exclude: /node_modules/,
          use: 'babel-loader',
        }, {
          test: /\.svg$/,
          include: /assets/,
          use: ['babel-loader', 'svg-react-loader'],
        }
      ]
    },
    resolve: {
      modules: [
        'node_modules',
      ],
    },
  };
};
```
chatBubble.jsx:
```js
import React from 'react';
import ReactDOM from 'react-dom';
import bubbleIcon from '../assets/bubble.svg'; // TODO: doesn't show properly yet

const buttonStyle = {
  width: 500,
  height: 500,
  position: 'absolute',
  bottom: 3,
  right: 3
};

const bubbleButton = () => (
  <button style={buttonStyle}>
    <bubbleIcon />
    <span>bubble</span>
  </button>
);

export default bubbleButton;
```
index.jsx (mainly for HMR):
```js
import React from 'react';
import ReactDOM from 'react-dom';
// AppContainer is a necessary wrapper component for HMR
import { AppContainer } from 'react-hot-loader';
import chatBubble from './chatBubble.jsx';

const render = (Component) => {
  ReactDOM.render(
    <AppContainer>
      <Component/>
    </AppContainer>,
    document.getElementById('root')
  );
};

render(chatBubble);

// Hot Module Replacement API
if (module.hot) {
  module.hot.accept('./chatBubble.jsx', () => {
    render(chatBubble)
  });
}
```

**Comment by jhamlet** [comment]
@Mingling94 You're configuration is using `react-svg-loader` not `svg-react-loader`

Also, you probably want an `include` and/or `exclude` directive on that loader configuration (limit it to a specific folder, or exclude font folders, etc...)

**Comment by Mingling94** [comment]
@jhamlet Oh sorry, I did make that error before and fixed it. I just pasted the erroneous code in. Now updated, could I bother you for another glance?

Thanks for the `include` suggestion :)

**Comment by jhamlet** [comment]
@Mingling94 Looking closer I see that your Element's tab is showing the element actually as a `<buttonicon>` tag. Which I would expect to see `<svg...>`

What do the contents of your `bubble.svg` look like?

**Comment by Mingling94** [comment]
Same, I thought that odd. I've never gotten it to show as an `<svg>` element.
bubble.svg:
```svg
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 14.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 43363)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="201px" height="96px" viewBox="0 0 201 96" enable-background="new 0 0 201 96" xml:space="preserve">
<path fill-rule="evenodd" clip-rule="evenodd" fill="#FFFFFF" d="M153,96H13C5.847,96,0,90.156,0,83V13C0,5.844,5.844,0,13,0h140
	c26.508,0,48,21.492,48,48S179.507,96,153,96"/>
<path fill-rule="evenodd" clip-rule="evenodd" fill="#6ACFE8" d="M153,93c24.853,0,45-20.147,45-45c0-24.853-20.147-45-45-45H13
	C7.503,3,3,7.503,3,13v70c0,5.496,4.5,10,10,10H153z"/>
<path fill-rule="evenodd" clip-rule="evenodd" fill="#FFFFFF" d="M153,12c-19.883,0-36,16.118-36,36s16.117,36,36,36
	c19.882,0,36-16.118,36-36S172.881,12,153,12"/>
<path fill-rule="evenodd" clip-rule="evenodd" fill="#6ACFE8" d="M153,41.581c3.545,0,6.42,2.874,6.42,6.42
	c0,3.545-2.875,6.42-6.42,6.42c-3.546,0-6.42-2.875-6.42-6.42C146.58,44.455,149.454,41.581,153,41.581 M153,34.119
	c7.666,0,13.881,6.215,13.881,13.882c0,2.202-0.514,4.285-1.427,6.135l0.432-0.269c0,0-0.994,2.771-0.497,4.762
	s0.497,4.478,0.497,4.478s-0.497-0.498-2.279-1.225c-1.249-0.509-5.949-0.305-8.655-0.137c-0.638,0.09-1.289,0.137-1.951,0.137l0,0
	c-7.667,0-13.882-6.215-13.882-13.881C139.118,40.333,145.333,34.119,153,34.119z M153,24.801c12.812,0,23.198,10.387,23.198,23.199
	v18.09c0,2.821-2.287,5.108-5.108,5.108c-2.457,0-4.509-1.734-4.998-4.046c-3.726,2.553-8.234,4.046-13.092,4.046
	C140.187,71.199,129.8,60.812,129.8,48C129.8,35.188,140.187,24.801,153,24.801z"/>
</svg>
```

**Comment by Mingling94** [comment]
@jhamlet Hey, any ideas on what I may be doing wrong? Want to look at my repo for a full view of the project?

**Comment by jhamlet** [comment]
@Mingling94 Yeah. That could help.

Also, you arer using the public release of `svg-react-loader@0.3.7` correct? I did a re-write that no longer requires babel if you install `svg-react-loader@next` I wonder if that might solve this?

I haven't released it yet, as I'm still hoping to get more testing done (using Enzyme), but have not had the bandwidth.

;-j

**Comment by Mingling94** [comment]
@jhamlet  installed `svg-react-loader@next` and it installed `^0.4.0-beta.2` which worked for me. Thanks! I'm still not sure why the public release wasn't working for me.

**Comment by gibson** [comment]
your problem in `import bubbleIcon from '../assets/bubble.svg';` component name))) Please read react docs 

> Caveat:
Always start component names with a capital letter.
For example, <div /> represents a DOM tag, but <Welcome /> represents a component and requires Welcome to be in scope.

**Comment by RomainGoncalves** [comment]
Thanks @gibson I had the same issue
