### ISSUE TITLE
error if filename starts with a number or other character not allowed in a function name

### ISSUE THREAD

**Issue by heygrady** [jhamlet/svg-react-loader#61]
When a filename starts with an illegal character this loader produces JS that is invalid.

- `72-filename.svg` fails
- `filename.svg` works

Expected: should sanitize the filename be prefixing with an `_` if it starts with an improper character. Should replace other "bad variable names" with `_`.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#Variables

**Comment by aliciacatalina** [comment]
Which is the duplicate of this issue? I'm facing the same problem.

**Comment by jhamlet** [comment]
@aliciacatalina As a work-a-round try putting something like `svg-react-loader?name=SVGReactComponent` in your webpack loader configuration, or in the individual import statement.
