### ISSUE TITLE
On 0.4, I'm getting `Module build failed: Error: A valid query string passed to parseQuery should begin with '?'`

### ISSUE THREAD

**Issue by jameydeorio** [jhamlet/svg-react-loader#62]
```
ERROR in ./shape-react-core/~/svg-react-loader/lib/loader.js?name=Icon!./shape-react-core/images/books.svg
Module build failed: Error: A valid query string passed to parseQuery should begin with '?'
    at Object.parseQuery (/Users/jameydeorio/dev/orm/frontend/node_modules/loader-utils/lib/parseQuery.js:13:9)
    at Object.svgReactLoader (/Users/jameydeorio/dev/orm/frontend/shape-react-core/node_modules/svg-react-loader/lib/loader.js:25:28)
```

Webpack config:

```
{
        test: /\.svg$/,
        exclude: /node_modules/,
        loader: 'svg-react'
      }
```

Import statement:

`import Icon from 'svg-react?name=Icon!../../images/books.svg'`

**Comment by kasperpihl** [comment]
I've just ran into the same issue. +1

**Comment by jameydeorio** [comment]
FWIW I was hitting this same issue with 0.3 under certain configurations as well.

**Comment by Artkoch** [comment]
Same issue. Is there a workaround?

**Comment by cescoferraro** [comment]
@jameydeorio  thats because the you are not passing a query parameter at all to webpack

https://github.com/jhamlet/svg-react-loader/blob/version-0.4.0/README.md#examples

Anyhow, then I get `Module build failed: TypeError: query.substr is not a function`

**Comment by halt-hammerzeit** [comment]
For anyone coming here: obviously this project is long time abandoned.
I suggest everyone migrate to `react-svg-loader@2.0.0-alpha.1`
https://github.com/boopathi/react-svg-loader

The webpack config stays the same, just `svg-react-loader` string is replaced by `react-svg-loader`.

**Comment by halt-hammerzeit** [comment]
For anyone who read my previous comment about migrating to `react-svg-loader` – I'm migrating back to this library.
The reason is that `react-svg-loader` feels less convenient ([and apparently has bugs](https://github.com/boopathi/react-svg-loader/issues/169)) and this library's author has finally fixed this issue.
