### ISSUE TITLE
Update the documentation to include the new `-loader` requirement

### ISSUE THREAD

**Issue by jameydeorio** [jhamlet/svg-react-loader#63]
Versions:

```
react: 15.4.2
npm: 4.1.2
node: 7.6.0
```

I think it's the version of React, but it may be one of the others, but using loaders now requires that you suffix them with `-loader`, like `loader: 'babel-loader?presets[]=es2015,presets[]=react!svg-react-loader'` in your webpack config. Otherwise, the build fails.

**Comment by epeterson320** [comment]
This is required by Webpack 2, and it would be a good idea to change the docs to include the `-loader` suffix regardless.
