### ISSUE TITLE
Loader have React depreceted warnings

### ISSUE THREAD

**Issue by konstantin24121** [jhamlet/svg-react-loader#66]
React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

[ReactBlog](https://facebook.github.io/react/blog/)

I think we must fix it, or loader will not work with React 16.0 

https://github.com/jhamlet/svg-react-loader/blob/master/utility/template.txt#L4

**Comment by hazratgs** [comment]
When will this bug be fixed?

**Comment by konstantin24121** [comment]
When owner merge #67 i mean. In my project i use fork

**Comment by IanVS** [comment]
Ergh, with no changelog and no merged PRs, it's pretty difficult to tell what minimum version I need to upgrade to in order to avoid the deprecation warnings.
