### ISSUE TITLE
Whitespace in filename bug

### ISSUE THREAD

**Issue by halt-hammerzeit** [jhamlet/svg-react-loader#72]
```js
import Person_add_icon from '../../../../assets/images/icons/person add.svg'
```

Is converted into
```js
function Person add (props) {
```
You should replace all whitespace `string.replace(/\s/g, '')`.
And what if the filename starts, say, with a digit.
Or contains a dot.
You should just leave it as SVG.

**Comment by jhamlet** [comment]
I think just defaulting to 'SvgReactComponent' and only overriding it when a 'name' parameter is given is the best way to go.

**Comment by jessy1092** [comment]
I think #71 would fix this issue. It could pass `titleCaseDelim: /[\s]/` to handle witespace.

**Comment by jhamlet** [comment]
Fixed by #71

**Comment by halt-hammerzeit** [comment]
Version `0.4.4`, still the same error.

**Comment by jhamlet** [comment]
@halt-hammerzeit Are you using the new `titleCaseDelim` parameter to specify your own delimiter (eg.: `/\s+/g`)?

**Comment by halt-hammerzeit** [comment]
@jhamlet Oh, a parameter has to be customized.
Ok, thx for the tip.
Still my opinion is the same: it should have included whitespace in`titleCaseDelim` by default.

**Comment by jhamlet** [comment]
@halt-hammerzeit Still thinking of changing to defaulting to `SVGReactComponent` if there is no `name` parameter given. This way I can forgo having to parse the fifteen million ways people want to name their files.

Another option is to allow for a `function` as the `name` parameter that receives the filename, and then individuals can customize if they really want to.
