### ISSUE TITLE
Load icon from SVG group

### ISSUE THREAD

**Issue by skolmer** [jhamlet/svg-react-loader#8]
Allow loading icons from SVG groups.
This feature would be helpful to load icon sets that are defined in a single SVG file. For example: https://materialdesignicons.com/getting-started (Angular Material -> Download mdi.svg)

**Comment by jhamlet** [comment]
I'm not sure I understand your request. It is not apparent from the link you gave.

Can you give me a sample of what you are trying to accomplish?

**Comment by skolmer** [comment]
Hi, sorry for the confusing link. I will try to clarify this a little bit more. 
On the materialdesignicons.com page is under "Angular Material" a download link to download all materialdesignicons as one big SVG file. Each icon is put in a named group in the SVG file. 
It would be nice if I could extract any of these icons from the SVG file with
`import { AccountBox, AccountAlert } from '.\md.svg'; `

**Comment by jhamlet** [comment]
That doesn't seem like something I would want to add.

Although, your use-case does raise the issue that I'm directly translating the SVG XML into Javascript and not using an intermediate XML to Javascript Object loader.

If I break out that piece, it would then allow another loader to "filter" (or "pick") from that intermediate object.

**Comment by skolmer** [comment]
how about looking for a child g element with a specified name in the XML root and replace the innerXml of the root XML element with the innerXml of the g element before translation of XML to JS.
maybe this would make it easier: `import AccountBox from '.\md.svg?group=account-box';`

**Comment by jhamlet** [comment]
I opened https://github.com/jhamlet/svg-react-loader/issues/11 to address the issue I spoke of above.

After that, it would allow an intermediate loader to filter the SVG XML for specific icons, or other stuff I haven't thought of yet.
