### ISSUE TITLE
how to provide independent scope for each svg component? 

### ISSUE THREAD

**Issue by huyansheng3** [jhamlet/svg-react-loader#85]
![image](https://user-images.githubusercontent.com/11534583/32307172-272a9942-bf4d-11e7-86b5-cce6d5e3cbdc.png)
in two svg file ,all define the same id ! but then later id cannot working ! so how to provider independent scope for each svg component ?

**Comment by nebaff** [comment]
id MUST be unique in all html page (or encapsutate svg in iframe)
you cannot violate this.

BUT in order to avoid problem you can use config param propsMap to revrite id to another propertyname : 

```
 example :
  propsMap: {
                     fillRule: 'fill-rule',
                     id: 'data-id'
                 },
```

**Comment by huyansheng3** [comment]
ok, have solved this problem with svgo-loader.
