### ISSUE TITLE
svg-react-loader with create-react-app - how to setup?

### ISSUE THREAD

**Issue by pauldcollins** [jhamlet/svg-react-loader#86]
I am getting the non-whitespace error when importing my SVG file with `create-react-app`

`Module build failed: Error: Non-whitespace before first tag.`

I've ejected my app and am trying to modify the `webpack.dev.config` file to ignore running the standard file-loader on my **svg** files and run the `svg-react-loader` instead.

I found some code from [this post](https://github.com/facebookincubator/create-react-app/issues/1388) and changed my filename to end in `inline.svg`, but trying to configure my webpack config doesn't seem to be working.

Here's my webpack config code:

```
// webpack.dev.config
oneOf: [
  {
    test: [/\.bmp$/, /\.gif$/, /\.jpe?g$/, /\.png$/],
    loader: require.resolve('url-loader'),
    options: {
      limit: 10000,
      name: 'static/media/[name].[hash:8].[ext]'
    }
  },
  {
    test: /\.inline\.svg$/,
    loader: require.resolve('svg-react-loader');
  },

  ....
  
  {
    exclude: [/\.js$/, /\.html$/, /\.json$/, /\.inline.svg$/],
    loader: require.resolve('file-loader'),
    options: {
      name: 'static/media/[name].[hash:8].[ext]'
    }
  }
]
```

I'm still getting the same whitespace error though. Thanks for any help.

**Comment by pauldcollins** [comment]
I managed to solve this, using a simple fix in [this post](https://github.com/facebookincubator/create-react-app/issues/1388)

Basically, just add a `-!` at the start of the import path. 

For example this:

```
import Logo from '-!svg-react-loader!./logo.svg';
```

**Comment by MarcoMedrano** [comment]
>  I should mention I didn't need to eject either
Thank u so much for that little text ↑, it worked for me either without of ejecting ttg
Just did:
`npm install svg-react-loader -D`

**Comment by davilima6** [comment]
The `!-` solution works until you run tests, which fail with:

```
Cannot find module '-!svg-react-loader!../../images/my-con.svg' from 'MyComponent.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous> (src/components/MyComponent/MyComponent.js:9:184)
```

Any known workaround?

**Comment by callmejm** [comment]
@pauldcollins you are the svg life saver !
