### ISSUE TITLE
classIdPrefix interpolations broken

### ISSUE THREAD

**Issue by jak3122** [jhamlet/svg-react-loader#88]
It looks like using a `classIdPrefix` string with interpolations like `[name]` through a webpack config is broken. I think it is due to a typo [here](https://github.com/jhamlet/svg-react-loader/blob/bcf37801405fb704d33fc6982fde885bccefc86f/lib/loader.js#L71), `classIdPref` instead of `classIdPrefix`.

The example from the readme using `classIdPrefix: '[name]-[hash:8]__'` uses the literal string as a prefix instead of interpolating it. Using `classIdPrefix: true` to use the name as a prefix does work.

**Comment by Strangehill** [comment]
I'm having this issue with the gatsby plugin.... can't even get `classIdPrefix: true` to work. What is this a duplicate of?
